// Generated by CoffeeScript 1.10.0
(function() {
  var brain, defaultVector, defuzz, fileReader, fs, generate, prevVector, readline, train, vectors;

  brain = require('brain');

  fs = require('fs');

  readline = require('readline');

  defaultVector = function() {
    var j, results;
    results = [];
    for (j = 0; j < 100; j++) {
      results.push(null);
    }
    return results;
  };

  vectors = [];

  prevVector = defaultVector();

  defuzz = function(vector) {
    var cumulative, index, interval, j, len, rand, results, vectorSum;
    vectorSum = vector.reduce(function(a, b) {
      return a + b;
    });
    rand = Math.random() * vectorSum;
    cumulative = 0;
    results = [];
    for (index = j = 0, len = vector.length; j < len; index = ++j) {
      interval = vector[index];
      cumulative = cumulative + interval;
      if (rand < cumulative) {
        console.log(index);
        break;
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  generate = function(net) {
    var i, j, output, results;
    prevVector = defaultVector();
    results = [];
    for (i = j = 1; j <= 100; i = j += 1) {
      output = net.run(prevVector);
      defuzz(output);
      results.push(prevVector = output);
    }
    return results;
  };

  train = function() {
    var net, stat;
    net = new brain.NeuralNetwork();
    stat = net.train(vectors, {
      errorThresh: 0.0085
    });
    console.warn(stat);
    return generate(net);
  };

  fileReader = readline.createInterface({
    input: fs.createReadStream('numbers'),
    terminal: false
  });

  fileReader.on('line', function(line) {
    var noteNumber, vector;
    noteNumber = parseInt(line, 10);
    if (!noteNumber) {
      return;
    }
    vector = defaultVector();
    vector[noteNumber] = 1;
    vectors.push({
      input: prevVector,
      output: vector
    });
    return prevVector = vector;
  });

  fileReader.on('close', train);

}).call(this);
